#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

xrandr --dpi 144		# Set DPI. User may want to use a larger number for larger screens.
# setbg & 			# set the background with the `setbg` script
xrdb "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources" & xrdbpid=$!	# use Xresources colors/settings
setcolors >/dev/null 2>&1 &
remaps &		# run the remaps script, switching caps/esc and more; check it for more info

autostart="mpd dunst unclutter pipewire xcompmgr"
( sctd -h >/dev/null ) && sctd --latitude 49.8407 --longitude 24.0334 2>&1 &

for program in $autostart; do
	pidof -sx "$program" || "$program" &
done >/dev/null 2>&1

# xcompmgr -f -F -D 3 &

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
